--- 
- 
  become: true
  hosts: all
  tasks: 
    - 
      name: "Stop the container"
      Shell: "docker stop jon
      name: "Delete the container"
      Shell: "docker rm container"
      name: "create docker container"
      shell: "docker run -d --name jon -p 1234:8080 prathyushasp/jon"
